
version: '3'

services:
  server:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8002:8000"
    external_links:
     - psql-11-kvs_db:kvs_db
