version: '3'

services:
  db:
    container_name: postgres
    image: mdillon/postgis:11-alpine
    restart: on-failure
    ports:
     - "5429:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
 
  server:
    build: .
    container_name: kvs_db
    env_file: .env
    image: kvs
    restart: on-failure
    command: ./docker-entrypoint.local.sh
    ports:
      - "8021:8001"
    volumes:
      - ./media:/code/media
      - ./static:/code/static
      - .:/code

    depends_on:
      - db