# Generated by Django 2.0.5 on 2020-01-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='ward',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
