# Generated by Django 2.0.5 on 2020-01-20 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userrole_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='core.District'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='core.Municipality'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='core.Province'),
        ),
    ]
