# Generated by Django 2.0.5 on 2019-12-19 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='core.District'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='core.Municipality'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='core.Province'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to=settings.AUTH_USER_MODEL),
        ),
    ]
