# Generated by Django 2.0.5 on 2020-01-29 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200128_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward', to='core.District')),
            ],
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='boundary',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='hlcit_code',
        ),
        migrations.AddField(
            model_name='ward',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward', to='core.Municipality'),
        ),
        migrations.AddField(
            model_name='ward',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ward', to='core.Province'),
        ),
    ]
