# Generated by Django 2.0.5 on 2020-01-29 10:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200129_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='municipality',
            name='hlcit_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
