# Generated by Django 2.0.5 on 2020-01-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200130_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='householddata',
            name='owned_land_image_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
