# Generated by Django 2.0.5 on 2019-12-23 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191223_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthnicityList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GenderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HouseTypeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LatrineList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MotherTongueList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OwnershipList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PermitList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReligionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoadCapacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoadType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WhoseOwnershipList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='InvolvedInSimulationList',
            new_name='EducationList',
        ),
        migrations.AlterField(
            model_name='copingmechanism',
            name='coping_medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coping_mechanism', to='core.CopingMechanismList'),
        ),
        migrations.AlterField(
            model_name='disasterpreparednessmechanism',
            name='preparedness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disaster_prepare', to='core.DisasterPreparednessMechanismList'),
        ),
        migrations.AlterField(
            model_name='drinkingwater',
            name='drinking_water',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drinking_water', to='core.DrinkingWaterList'),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility', to='core.FacilityList'),
        ),
        migrations.AlterField(
            model_name='foodeaten',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_eaten', to='core.FoodChoice'),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='fuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel', to='core.FuelTypeList'),
        ),
        migrations.AlterField(
            model_name='informationmedium',
            name='info_medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_medium', to='core.InformationMediumList'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='core.InsuranceList'),
        ),
        migrations.AlterField(
            model_name='involvedinsimulation',
            name='simulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulation', to='core.DisasterList'),
        ),
        migrations.AlterField(
            model_name='materialsinnearestmarket',
            name='material_in_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_material', to='core.MaterialsInNearestMarketList'),
        ),
        migrations.AlterField(
            model_name='technicalfield',
            name='technical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_man', to='core.TechnicalField'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='core.VehicleList'),
        ),
        migrations.AlterField(
            model_name='wardfallingpronearea',
            name='prone_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ward_prone', to='core.DisasterList'),
        ),
        migrations.AlterField(
            model_name='warningmediumsuitablefordisaster',
            name='warning_medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warn_medium', to='core.WarningMediumList'),
        ),
        migrations.AlterField(
            model_name='workdoneonflood',
            name='work_done',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_done', to='core.WorkDoneOnFloodList'),
        ),
    ]
