# Generated by Django 2.0.5 on 2020-02-28 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_householddata_owned_land_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house_gallery')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.HouseHoldData')),
            ],
        ),
    ]
