# Generated by Django 2.0.5 on 2020-03-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaldetaildata',
            name='animal_type_other',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerfamilydata',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
