# Generated by Django 2.0.5 on 2019-12-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191223_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymembercriterialist',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ownerfamily',
            name='family_member_criteria',
            field=models.IntegerField(choices=[(1, 'Senior citizen of 70 years'), (1, 'Senior Citizen of 60 years'), (1, 'Unmarried 60 years old woman'), (1, '60 years old single woman'), (1, 'Widow of any age'), (1, 'People with disability of any age'), (1, 'People with disability of any age (Received a red color blindness id card from Department of Women and Children)'), (1, 'People with disability of any age (Received a blue color blindness id card from Department of Women and Children)'), (1, 'Endangered tribes of any age (bankariya, raute, surel, hayu, raaji, kisan, lepcha, meche, kusbadiya (pattharkatta, silakat, kushbadhiyaa, kuchbadhiya) ethnic citizens'), (1, 'Children under 5 years of age, Dalit from all over the country and children under 5 years of age from accham, bajhang, rautahat, jumla, humla, mugu, kalikot, dolpa, mahottari, sarlahi, doti, jajarkot, bajura and siraha)'), (1, 'None of these above')], default=1),
        ),
    ]
