# Generated by Django 2.0.5 on 2020-03-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200305_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='householddata',
            name='flood_resilience_work',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
