# Generated by Django 3.0 on 2020-09-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200924_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householddata',
            name='risk_score',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
    ]
