# Generated by Django 2.0.5 on 2019-12-24 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_chronicillnessdata_disabilitydata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familydisability',
            name='owner_family',
        ),
        migrations.AlterField(
            model_name='guideline',
            name='house_hold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guide_line', to='core.HouseHold'),
        ),
        migrations.AlterField(
            model_name='whoseownershipdata',
            name='house_hold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whose_ownership', to='core.HouseHold'),
        ),
        migrations.AlterField(
            model_name='whoseownershipdata',
            name='ownership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whose_ownership', to='core.WhoseOwnershipList'),
        ),
        migrations.DeleteModel(
            name='FamilyDisability',
        ),
    ]
