# Generated by Django 2.0.5 on 2019-12-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191224_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='household',
            old_name='index',
            new_name='indx',
        ),
    ]
