# Generated by Django 3.0 on 2020-09-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200924_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='householddata',
            name='risk_type',
            field=models.CharField(blank=True, choices=[('Least Vulnerable', 'Least Vulnerable'), ('Medium Vulnerable', 'Medium Vulnerable'), ('Highly Vulnerable', 'Highly Vulnerable')], max_length=30, null=True),
        ),
    ]
