# Generated by Django 2.0.5 on 2020-01-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_householddata_ward_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animaldetaildata',
            old_name='is_it_for_commercial_purpose',
            new_name='is_it_for_commercial_purpose_en',
        ),
        migrations.RenameField(
            model_name='animaldetaildata',
            old_name='type',
            new_name='is_it_for_commercial_purpose_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='altitude',
            new_name='altitude_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='house_num',
            new_name='altitude_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='capacity_of_evacuation_center',
            new_name='capacity_of_evacuation_center_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='carpenter_sex_female_number',
            new_name='capacity_of_evacuation_center_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='carpenter_sex_male_number',
            new_name='carpenter_sex_female_number_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='citizenship_num',
            new_name='carpenter_sex_female_number_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='contingency_plan',
            new_name='carpenter_sex_male_number_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='coping_mechanism',
            new_name='carpenter_sex_male_number_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='coping_mechanism_other_mention',
            new_name='citizenship_num_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='disaster_risk_management_other_mention',
            new_name='citizenship_num_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='disaster_type_other_mention',
            new_name='contingency_plan_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='distance_alternative_market',
            new_name='contingency_plan_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='distance_to_evacuation_center',
            new_name='coping_mechanism_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='distance_to_nearest_open_space',
            new_name='coping_mechanism_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='distance_to_safe_place',
            new_name='coping_mechanism_other_mention_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='doctor_sex_female_number',
            new_name='coping_mechanism_other_mention_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='damages_occurred_during_earthquake',
            new_name='damages_occurred_during_earthquake_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='damages_occurred_during_earthquake_other_mention',
            new_name='damages_occurred_during_earthquake_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='damages_occurred_during_fire',
            new_name='damages_occurred_during_earthquake_other_mention_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='damages_occurred_during_fire_other_mention',
            new_name='damages_occurred_during_earthquake_other_mention_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='damages_occurred_during_flood',
            new_name='damages_occurred_during_fire_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='damages_occurred_during_flood_other_mention',
            new_name='damages_occurred_during_fire_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='damages_occurred_during_landslide',
            new_name='damages_occurred_during_fire_other_mention_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='damages_occurred_during_landslide_other_mention',
            new_name='damages_occurred_during_fire_other_mention_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='house_damage_type',
            new_name='damages_occurred_during_flood_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='house_damage_type_earthquake',
            new_name='damages_occurred_during_flood_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='house_damage_type_earthquake_other_mention',
            new_name='damages_occurred_during_flood_other_mention_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='house_damage_type_fire',
            new_name='damages_occurred_during_flood_other_mention_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='house_damage_type_fire_other_mention',
            new_name='damages_occurred_during_landslide_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='house_damage_type_landslide',
            new_name='damages_occurred_during_landslide_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='house_damage_type_other_mention',
            new_name='damages_occurred_during_landslide_other_mention_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='migrated_in_the_time_of_earthquake',
            new_name='damages_occurred_during_landslide_other_mention_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='doctor_sex_male_number',
            new_name='disaster_risk_management_other_mention_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='does_ward_has_evacuation_center',
            new_name='disaster_risk_management_other_mention_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='duration_of_loan',
            new_name='disaster_type_other_mention_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='easily_materials_available',
            new_name='disaster_type_other_mention_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='electrician_sex_female_number',
            new_name='distance_alternative_market_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='electrician_sex_male_number',
            new_name='distance_alternative_market_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='engineer_sex_female_number',
            new_name='distance_to_evacuation_center_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='engineer_sex_male_number',
            new_name='distance_to_evacuation_center_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='established_year',
            new_name='distance_to_nearest_open_space_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='facility_if_other_mention',
            new_name='distance_to_nearest_open_space_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='flood_activities_if_other_mention',
            new_name='distance_to_safe_place_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='fuel_if_other_mention',
            new_name='distance_to_safe_place_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='ha_lab_sex_female_number',
            new_name='doctor_sex_female_number_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='ha_lab_sex_male_number',
            new_name='doctor_sex_female_number_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='has_flood_effect_tube_well',
            new_name='doctor_sex_male_number_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='hazard_type_other_mention',
            new_name='doctor_sex_male_number_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='house_has_emergency_kit',
            new_name='does_ward_has_evacuation_center_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='house_if_other_mention',
            new_name='does_ward_has_evacuation_center_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='identified_safe_place_in_flood',
            new_name='duration_of_loan_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='if_no_material_management',
            new_name='duration_of_loan_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='if_other_business_mention',
            new_name='easily_materials_available_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='if_other_occupation',
            new_name='easily_materials_available_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='if_other_small_business_mention',
            new_name='electrician_sex_female_number_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='information_medium_other_mention',
            new_name='electrician_sex_female_number_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='involved_in_dprc_guideline',
            new_name='electrician_sex_male_number_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='involved_in_ldcrp_guideline',
            new_name='electrician_sex_male_number_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='jt_or_jta_sex_female_number',
            new_name='engineer_sex_female_number_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='jt_or_jta_sex_male_number',
            new_name='engineer_sex_male_number_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='know_about_drpc_guideline',
            new_name='established_year_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='know_about_ldcrp_guideline',
            new_name='established_year_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='loan_amount',
            new_name='facility_if_other_mention_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='market_available_other_mention',
            new_name='facility_if_other_mention_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='market_distance',
            new_name='flood_activities_if_other_mention_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='medium_suitable_for_ews',
            new_name='flood_activities_if_other_mention_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='monthly_expanses',
            new_name='fuel_if_other_mention_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='monthly_income',
            new_name='fuel_if_other_mention_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='name_alternative_market',
            new_name='ha_lab_sex_female_number_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='num_of_house_using_tube_well',
            new_name='ha_lab_sex_female_number_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='nurse_sex_female_number',
            new_name='ha_lab_sex_male_number_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='nurse_sex_male_number',
            new_name='ha_lab_sex_male_number_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='other_sex_female_number',
            new_name='has_flood_effect_tube_well_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='other_sex_male_number',
            new_name='has_flood_effect_tube_well_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='owner_age',
            new_name='hazard_type_other_mention_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='owner_contact',
            new_name='hazard_type_other_mention_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='migrated_in_the_time_of_fire',
            new_name='house_damage_type_earthquake_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='migrated_in_the_time_of_flood',
            new_name='house_damage_type_earthquake_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='migrated_in_the_time_of_landslide',
            new_name='house_damage_type_earthquake_other_mention_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='place_you_migrated_earthquake',
            new_name='house_damage_type_earthquake_other_mention_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='place_you_migrated_earthquake_other_mention',
            new_name='house_damage_type_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='place_you_migrated_fire',
            new_name='house_damage_type_fire_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='place_you_migrated_fire_other_mention',
            new_name='house_damage_type_fire_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='road_width',
            new_name='house_damage_type_fire_other_mention_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='plumber_sex_female_number',
            new_name='house_has_emergency_kit_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='responder_age',
            new_name='house_has_emergency_kit_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='plumber_sex_male_number',
            new_name='house_if_other_mention_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='responder_contact',
            new_name='house_if_other_mention_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='household_number',
            new_name='house_num_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='latitude',
            new_name='house_num_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='house_room',
            new_name='house_room_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='house_storey',
            new_name='house_room_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='longitude',
            new_name='household_number_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='owner_name',
            new_name='household_number_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='responder_name',
            new_name='identified_safe_place_in_flood_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='status_owner',
            new_name='identified_safe_place_in_flood_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='toilet_type_other_mention',
            new_name='if_business_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='vehicle_if_other_mention',
            new_name='if_business_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='veterinary_sex_female_number',
            new_name='if_no_material_management_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='veterinary_sex_male_number',
            new_name='if_no_material_management_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='ward_falling_prone_area',
            new_name='if_other_business_mention_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='warehouse_in_ward',
            new_name='if_other_business_mention_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='place_name',
            new_name='latitude_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='precision',
            new_name='latitude_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='survayor_name',
            new_name='longitude_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='ward_num',
            new_name='longitude_ne',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='if_business',
            new_name='manpower_other_en',
        ),
        migrations.RenameField(
            model_name='householddata',
            old_name='manpower_other',
            new_name='manpower_other_ne',
        ),
        migrations.RenameField(
            model_name='ownerfamilydata',
            old_name='age_group',
            new_name='age_group_en',
        ),
        migrations.RenameField(
            model_name='ownerfamilydata',
            old_name='chronic_illness_type_other_mention',
            new_name='age_group_ne',
        ),
        migrations.RenameField(
            model_name='ownerfamilydata',
            old_name='chronic_illness_type',
            new_name='chronic_illness_type_en',
        ),
        migrations.RenameField(
            model_name='ownerfamilydata',
            old_name='citizenship_number',
            new_name='chronic_illness_type_other_mention_en',
        ),
        migrations.RenameField(
            model_name='ownerfamilydata',
            old_name='education_level',
            new_name='chronic_illness_type_other_mention_ne',
        ),
        migrations.RenameField(
            model_name='ownerfamilydata',
            old_name='family_criteria_belonging_to',
            new_name='citizenship_number_en',
        ),
        migrations.RenameField(
            model_name='ownerfamilydata',
            old_name='family_member_meet_criteria',
            new_name='citizenship_number_ne',
        ),
        migrations.RenameField(
            model_name='ownerfamilydata',
            old_name='gender',
            new_name='education_level_en',
        ),
        migrations.RenameField(
            model_name='ownerfamilydata',
            old_name='if_other_occupation',
            new_name='education_level_ne',
        ),
        migrations.RenameField(
            model_name='ownerfamilydata',
            old_name='involvement_in_occupation',
            new_name='family_criteria_belonging_to_en',
        ),
        migrations.RenameField(
            model_name='ownerfamilydata',
            old_name='main_occupation_of_family',
            new_name='family_criteria_belonging_to_ne',
        ),
        migrations.RenameField(
            model_name='ownerfamilydata',
            old_name='monthly_income',
            new_name='family_member_meet_criteria_en',
        ),
        migrations.RenameField(
            model_name='ownerfamilydata',
            old_name='name',
            new_name='family_member_meet_criteria_ne',
        ),
        migrations.RenameField(
            model_name='ownerfamilydata',
            old_name='people_with_disability',
            new_name='gender_en',
        ),
        migrations.RenameField(
            model_name='ownerfamilydata',
            old_name='reasons_for_not_received_social_security',
            new_name='gender_ne',
        ),
        migrations.RenameField(
            model_name='ownerfamilydata',
            old_name='received_social_security',
            new_name='if_other_occupation_en',
        ),
        migrations.RemoveField(
            model_name='animaldetaildata',
            name='number',
        ),
        migrations.RemoveField(
            model_name='householddata',
            name='num_of_days_food_eaten_condiments',
        ),
        migrations.RemoveField(
            model_name='householddata',
            name='num_of_days_food_eaten_fruits',
        ),
        migrations.RemoveField(
            model_name='householddata',
            name='num_of_days_food_eaten_mean_and_fish',
        ),
        migrations.RemoveField(
            model_name='householddata',
            name='num_of_days_food_eaten_milk_products',
        ),
        migrations.RemoveField(
            model_name='householddata',
            name='num_of_days_food_eaten_oil_products',
        ),
        migrations.RemoveField(
            model_name='householddata',
            name='num_of_days_food_eaten_pulses',
        ),
        migrations.RemoveField(
            model_name='householddata',
            name='num_of_days_food_eaten_staples',
        ),
        migrations.RemoveField(
            model_name='householddata',
            name='num_of_days_food_eaten_sugar_products',
        ),
        migrations.RemoveField(
            model_name='householddata',
            name='num_of_days_food_eaten_vegetables',
        ),
        migrations.RemoveField(
            model_name='ownerfamilydata',
            name='people_with_disability_other_mention',
        ),
        migrations.AddField(
            model_name='animaldetaildata',
            name='number_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='animaldetaildata',
            name='number_ne',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='animaldetaildata',
            name='type_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='animaldetaildata',
            name='type_ne',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='house_damage_type_fire_other_mention_ne',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='house_damage_type_landslide_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='house_damage_type_landslide_ne',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='house_damage_type_ne',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='house_damage_type_other_mention_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='house_damage_type_other_mention_ne',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='house_storey_en',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='house_storey_ne',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='if_other_occupation_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='if_other_occupation_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='if_other_small_business_mention_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='if_other_small_business_mention_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='information_medium_other_mention_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='information_medium_other_mention_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='involved_in_dprc_guideline_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='involved_in_dprc_guideline_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='involved_in_ldcrp_guideline_em',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='involved_in_ldcrp_guideline_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='jt_or_jta_sex_female_number_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='jt_or_jta_sex_female_number_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='jt_or_jta_sex_male_number_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='jt_or_jta_sex_male_number_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='know_about_drpc_guideline_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='know_about_drpc_guideline_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='know_about_ldcrp_guideline_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='know_about_ldcrp_guideline_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='loan_amount_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='loan_amount_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='market_available_other_mention_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='market_available_other_mention_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='market_distance_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='market_distance_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='medium_suitable_for_ews_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='medium_suitable_for_ews_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='migrated_in_the_time_of_earthquake_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='migrated_in_the_time_of_earthquake_ne',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='migrated_in_the_time_of_fire_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='migrated_in_the_time_of_fire_ne',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='migrated_in_the_time_of_flood_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='migrated_in_the_time_of_flood_ne',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='migrated_in_the_time_of_landslide_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='migrated_in_the_time_of_landslide_ne',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='monthly_expanses_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='monthly_expanses_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='monthly_income_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='monthly_income_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='name_alternative_market_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='name_alternative_market_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='num_of_days_food_eaten_condiments_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='num_of_days_food_eaten_condiments_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='num_of_days_food_eaten_fruits_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='num_of_days_food_eaten_fruits_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='num_of_days_food_eaten_mean_and_fish_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='num_of_days_food_eaten_mean_and_fish_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='num_of_days_food_eaten_milk_products_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='num_of_days_food_eaten_milk_products_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='num_of_days_food_eaten_oil_products_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='num_of_days_food_eaten_oil_products_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='num_of_days_food_eaten_pulses_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='num_of_days_food_eaten_pulses_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='num_of_days_food_eaten_staples_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='num_of_days_food_eaten_staples_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='num_of_days_food_eaten_sugar_products_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='num_of_days_food_eaten_sugar_products_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='num_of_days_food_eaten_vegetables_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='num_of_days_food_eaten_vegetables_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='num_of_house_using_tube_well_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='num_of_house_using_tube_well_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='nurse_sex_female_number_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='nurse_sex_female_number_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='nurse_sex_male_number_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='nurse_sex_male_number_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='other_sex_female_number_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='other_sex_female_number_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='other_sex_male_number_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='other_sex_male_number_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='owner_age_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='owner_age_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='owner_contact_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='owner_contact_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='owner_name_en',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='owner_name_ne',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='place_name_en',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='place_name_ne',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='place_you_migrated_earthquake_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='place_you_migrated_earthquake_ne',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='place_you_migrated_earthquake_other_mention_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='place_you_migrated_earthquake_other_mention_ne',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='place_you_migrated_fire_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='place_you_migrated_fire_ne',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='place_you_migrated_fire_other_mention_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='place_you_migrated_fire_other_mention_ne',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='plumber_sex_female_number_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='plumber_sex_female_number_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='plumber_sex_male_number_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='plumber_sex_male_number_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='precision_en',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='precision_ne',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='responder_age_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='responder_age_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='responder_contact_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='responder_contact_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='responder_name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='responder_name_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='road_width_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='road_width_ne',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='status_owner_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='survayor_name_en',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='survayor_name_ne',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='today',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='toilet_type_other_mention_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='toilet_type_other_mention_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='vehicle_if_other_mention_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='vehicle_if_other_mention_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='veterinary_sex_female_number_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='veterinary_sex_female_number_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='veterinary_sex_male_number_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='veterinary_sex_male_number_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='ward_falling_prone_area_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='ward_falling_prone_area_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='ward_num_en',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='ward_num_ne',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='warehouse_in_ward_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='householddata',
            name='warehouse_in_ward_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ownerfamilydata',
            name='chronic_illness_type_ne',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ownerfamilydata',
            name='if_other_occupation_ne',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ownerfamilydata',
            name='involvement_in_occupation_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ownerfamilydata',
            name='involvement_in_occupation_ne',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ownerfamilydata',
            name='main_occupation_of_family_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ownerfamilydata',
            name='main_occupation_of_family_ne',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ownerfamilydata',
            name='monthly_income_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ownerfamilydata',
            name='monthly_income_ne',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ownerfamilydata',
            name='name_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ownerfamilydata',
            name='name_ne',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ownerfamilydata',
            name='people_with_disability_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ownerfamilydata',
            name='people_with_disability_ne',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ownerfamilydata',
            name='people_with_disability_other_mention_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ownerfamilydata',
            name='people_with_disability_other_mention_ne',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ownerfamilydata',
            name='reasons_for_not_received_social_security_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ownerfamilydata',
            name='reasons_for_not_received_social_security_ne',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ownerfamilydata',
            name='received_social_security_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ownerfamilydata',
            name='received_social_security_ne',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ownerfamilydata',
            name='chronic_illness_type_aids',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ownerfamilydata',
            name='chronic_illness_type_alzheimer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ownerfamilydata',
            name='chronic_illness_type_asthama',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ownerfamilydata',
            name='chronic_illness_type_cancer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ownerfamilydata',
            name='chronic_illness_type_diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ownerfamilydata',
            name='chronic_illness_type_heart_diseases',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ownerfamilydata',
            name='chronic_illness_type_kidney_diseases',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ownerfamilydata',
            name='chronic_illness_type_other',
            field=models.BooleanField(default=False),
        ),
    ]
