# Generated by Django 2.0.5 on 2020-01-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200102_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerfamilydata',
            old_name='family_criteria_belonging_to',
            new_name='occupation',
        ),
        migrations.RemoveField(
            model_name='ownerfamilydata',
            name='family_criteria_belonging_other_mention',
        ),
        migrations.RemoveField(
            model_name='ownerfamilydata',
            name='family_member_meet_criteria',
        ),
        migrations.RemoveField(
            model_name='ownerfamilydata',
            name='occupatin',
        ),
        migrations.RemoveField(
            model_name='ownerfamilydata',
            name='reasons_for_not_received_social_security_ne',
        ),
        migrations.AddField(
            model_name='ownerfamilydata',
            name='chronic_illness_other',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
