# Generated by Django 2.0.5 on 2020-01-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200107_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='householddata',
            name='id',
        ),
        migrations.AlterField(
            model_name='householddata',
            name='index',
            field=models.CharField(default=1, max_length=1000, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
