# Generated by Django 2.0.5 on 2020-01-07 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200107_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherfamilymember',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='other_family_member', to='core.HouseHoldData'),
            preserve_default=False,
        ),
    ]
