# Generated by Django 2.0.5 on 2020-01-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_otherfamilymember_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householddata',
            name='technical_manpower_presence',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
