# Generated by Django 2.0.5 on 2020-01-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(upload_to='image')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=500)),
                ('location_icon', models.ImageField(upload_to='icon')),
                ('number', models.CharField(max_length=500)),
                ('number_icon', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('email_icon', models.EmailField(max_length=254)),
                ('footer_txt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
                ('title', models.CharField(max_length=500)),
                ('logo', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='OurMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('logo1', models.ImageField(upload_to='image')),
                ('logo2', models.ImageField(upload_to='image')),
                ('logo3', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='OverallSystemFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(upload_to='image')),
                ('title', models.CharField(max_length=500)),
                ('feature1', models.CharField(max_length=500)),
                ('feature2', models.CharField(max_length=500)),
                ('feature3', models.CharField(max_length=500)),
                ('feature4', models.CharField(max_length=500)),
                ('feature5', models.CharField(max_length=500)),
                ('feature6', models.CharField(max_length=500)),
                ('feature7', models.CharField(max_length=500)),
                ('feature8', models.CharField(max_length=500)),
            ],
        ),
    ]
