# Generated by Django 3.0 on 2020-09-02 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('calculated_value', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('calculated_value', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('household_field_mapping', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('calculated_value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.Category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='parent_theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.Theme'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_choice', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('calculated_value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('parent_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.Question')),
            ],
        ),
    ]
