# Generated by Django 3.0 on 2020-09-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0004_auto_20200903_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mappable',
            field=models.BooleanField(default=True),
        ),
    ]
