# Generated by Django 3.0 on 2020-09-03 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0005_question_mappable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='mappable',
            new_name='directly_mappable',
        ),
    ]
