# Generated by Django 3.0 on 2020-09-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0007_auto_20200907_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='map_to_field_1',
            field=models.CharField(choices=[('substrings', 'scoring based on a fixed number of substrings'), ('yes/no', 'scoring based on simple yes or no'), ('keywords', 'scoring based on a fixed number of keywords'), ('composite_count', 'options varries from No to More than 1'), ('multifield_substring', 'one that combines data from 2 or more fields based on substrings'), ('range_based', 'options have some kind of range of values, e.g. distance 50-100 metre, 100-200 metre')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='map_to_field_2',
            field=models.CharField(blank=True, choices=[('substrings', 'scoring based on a fixed number of substrings'), ('yes/no', 'scoring based on simple yes or no'), ('keywords', 'scoring based on a fixed number of keywords'), ('composite_count', 'options varries from No to More than 1'), ('multifield_substring', 'one that combines data from 2 or more fields based on substrings'), ('range_based', 'options have some kind of range of values, e.g. distance 50-100 metre, 100-200 metre')], max_length=200, null=True),
        ),
    ]
