# Generated by Django 3.0 on 2020-09-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0012_auto_20200907_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='scoring_method',
            field=models.CharField(choices=[('substrings', 'scoring based on a fixed number of substrings'), ('yes/no', 'scoring based on simple yes or no'), ('keywords', 'scoring based on a fixed number of keywords'), ('code_mapping', 'certain coding mechanism in the data, e.g. number codes mentioned in data for different answer options'), ('composite_count', 'scoring options varries from No to More than 1'), ('multifield_substring', 'scoring based on combination of data from 2 or more fields based on substrings'), ('range_based', 'options have some kind of range of values, e.g. distance 50-100 metre, 100-200 metre')], default='substrings', max_length=200),
        ),
    ]
