# Generated by Django 3.0 on 2020-09-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0014_auto_20200909_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_types',
            field=models.CharField(choices=[('keywords', 'answer options exactly match with criteria in question'), ('substrings', 'answer should be derived from substring of the field data'), ('code_mapping', 'certain coding mechanism in the data, e.g. number codes mentioned in data for different answer options'), ('time_range_from_substring', 'time range need to be derived from substring of the field'), ('count_from_substring', 'count need to be derived from substring of the field'), ('complex_calculation', 'involves a number of factors ans fields to find the score'), ('with_blank_rows', 'data contains blank rows')], default='substrings', max_length=200),
        ),
    ]
