# Generated by Django 3.0 on 2020-09-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0017_auto_20200916_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_types',
            field=models.CharField(choices=[('keywords', 'answer options exactly match with criteria in question'), ('substrings', 'answer should be derived from substring of the field data'), ('code_mapping', 'certain coding mechanism in the data, e.g. number codes mentioned in data for different answer options'), ('multi_object_row', 'two or more data objects in same answer separated by /'), ('count_from_substring', 'count need to be derived from substring of the field'), ('complex_calculation', 'involves a number of factors ans fields to find the score'), ('with_blank_rows', 'data contains blank rows'), ('varying_data', 'data in each row can be different e.g. Citizenship Number')], default='substrings', max_length=200),
        ),
    ]
